#!/bin/sh


# dotfiles
alias config='/usr/bin/git --git-dir=$HOME/dotfiles/ --work-tree=$HOME'

# aliases
alias bed='xrandr --output HDMI-0 --mode 4096x2160 --scale 0.5x0.5 && echo "awesome.restart()" | awesome-client'
alias desk='xrandr --output HDMI-0 --mode 4096x2160 --scale 1x1 && echo "awesome.restart()" | awesome-client'
alias yeet='yay -Rns'
mkcd() {
    mkdir -p $1 && cd $1
}

i_am_boared() {
    boared_cmds=('pipes.sh -p 5 -t 1 -r 0' 'cmatrix' 'cbonsai -li' 'tty-clock -s -c -B -C 3 -f "%a. %d %B %Y"')
    rand=${boared_cmds[$RANDOM % ${#boared_cmds[@]-1}+1]}
    eval " $rand"
}

# ssh for kitty terminal
if [[ $TERM == "xterm-kitty" ]]; then
    alias ssh="kitty +kitten ssh"
fi

# get fastest mirrors
alias mirror='sudo reflector -f 30 -l 30 --number 10 --verbose --save /etc/pacman.d/mirrorlist'
alias mirrord='sudo reflector --latest 50 --number 20 --sort delay --save /etc/pacman.d/mirrorlist'
alias mirrors='sudo reflector --latest 50 --number 20 --sort score --save /etc/pacman.d/mirrorlist'
alias mirrora='sudo reflector --latest 50 --number 20 --sort age --save /etc/pacman.d/mirrorlist'

# modern replacment (exa) for ls
alias ls='exa --icons -a'

# Colorize ls output
#alias ls='ls --color=auto'

alias ps='procs'
alias grep='rg'
alias vim='nvim'
alias ...='cd ../..'
alias ....='cd ../../..'

# Colorize grep output (good for log files)
#alias grep='grep --color=auto'
#alias egrep='egrep --color=auto'
#alias fgrep='fgrep --color=auto'

# Colorize diff output (good for log files)
alias diff='diff --color=auto'

# Colorize ip output (good for log files)
alias ip='ip -color=auto'
