[config]
version_check = true

[templates.css]
input_path = '~/.config/matugen/templates/colors.css'
output_path = '~/.config/matugen/current-colors.css'

[templates.hyprland]
input_path = '~/.config/matugen/templates/hyprland-colors.conf'
output_path = '~/.config/hypr/colors.conf'
post_hook = 'hyprctl reload'

[templates.ags]
input_path = '~/.config/matugen/templates/colors.scss'
output_path = '~/.config/ags/scss/colors.scss'
post_hook = 'ags request "rebuild_colors" --instance astal'

[templates.kitty]
input_path = '~/.config/matugen/templates/kitty-colors.conf'
output_path = '~/.config/kitty/colors.conf'

[templates.starship]
input_path = '~/.config/matugen/templates/starship-colors.toml'
output_path = '~/.cache/matugen/starship.toml'
post_hook = '~/.config/matugen/scripts/starship.sh'

[templates.fox]
input_path = '~/.config/matugen/templates/fox-colors.json'
output_path = '~/.cache/wal/colors.json'
post_hook = 'pywalfox update'

[templates.bat]
input_path = '~/.config/matugen/templates/bat-colors.tmTheme'
output_path = '~/.config/bat/themes/matugen.tmTheme'
post_hook = 'bat cache --build'

[templates.ghostty]
input_path = '~/.config/matugen/templates/ghostty-colors'
output_path = '~/.config/ghostty/themes/matugen'
post_hook = 'systemctl reload --user app-com.mitchellh.ghostty.service'
