# Fish shell theme generated by matugen

set --global fish_color_normal e0e4db
set --global fish_color_command a1d39a
set --global fish_color_param baccb3
set --global fish_color_keyword a1d39a
set --global fish_color_quote a0cfd4
set --global fish_color_redirection a0cfd4 --bold
set --global fish_color_end c2c9bd
set --global fish_color_comment 8c9388
set --global fish_color_error ffb4ab
set --global fish_color_escape a0cfd4
set --global fish_color_operator a0cfd4
set --global fish_color_autosuggestion 8c9388
set --global fish_color_cancel -r
set --global fish_color_cwd a1d39a
set --global fish_color_cwd_root ffb4ab
set --global fish_color_user baccb3
set --global fish_color_host e0e4db
set --global fish_color_host_remote a0cfd4
set --global fish_color_status ffb4ab
set --global fish_color_valid_path --underline
set --global fish_color_history_current --bold
set --global fish_color_search_match --background=1d211b
set --global fish_color_selection --background=272b25
set --global fish_pager_color_completion e0e4db
set --global fish_pager_color_description 8c9388
set --global fish_pager_color_prefix a1d39a --bold --underline
set --global fish_pager_color_progress 0a390f --background=a1d39a
set --global fish_pager_color_selected_background -r
