#!/usr/bin/env bash

scale_factor=1.5

hypr_dir="$XDG_RUNTIME_DIR/hypr/$HYPRLAND_INSTANCE_SIGNATURE"
info="# Auto generated by $0"

readarray -t monitors < <(
    hyprctl monitors -j | jq -r '.[] | "\(.name),\(.width)x\(.height)@\(.refreshRate),\(.x)x\(.y),\(.scale)"'
)
content="$info
"

for monitor in "${monitors[@]}"; do
    name=$(echo "$monitor" | cut -d ',' -f1)
    scale=$(echo "$monitor" | cut -d ',' -f4)

    default_scale=$(
        rg monitor= ~/.config/hypr/conf/io/monitor.conf | rg "$name" | cut -d',' -f4
    )

    dir="$hypr_dir/temp/monitors/$name"
    # echo "$name { Scale: $scale, default: $default_scale, dir: $dir }"
    mkdir -p "$dir"

    if awk "BEGIN { exit !($scale > $default_scale) } "; then
        content+=$(echo "$monitor" | cut -d ',' -f-3 | xargs -I {} echo "monitor={}, $default_scale")
        echo "false" >"$dir/is_scaled"
    else
        new_scale=$(awk "BEGIN {print $scale_factor * $scale}")

        content+=$(echo "$monitor" | cut -d ',' -f-3 | xargs -I {} echo "monitor={}, $new_scale")
        echo "true" >"$dir/is_scaled"
    fi

    content+=$'\n'
    content+=$'\n'
done

content=$(echo -e "$content")

~/.config/hypr/scripts/utils/update_file.sh "temp/monitor_scale.conf" "$content" && swww restore
