#!/usr/bin/env bash

info="# Auto generated by $0"

scale_factor=1.5

readarray -t monitors < <(
    hyprctl monitors -j | jq -r '.[] | "\(.name),\(.width)x\(.height)@\(.refreshRate),\(.x)x\(.y),\(.scale)"'
)
content="$info
"

for monitor in "${monitors[@]}"; do
    name=$(echo "$monitor" | tr -d '-' | cut -d ',' -f1)
    scale=$(echo "$monitor" | cut -d ',' -f4)

    env_var_name="HYPR_MONITOR_$name"
    default_scale=${!env_var_name}
    # echo "$name: Scale is $scale, default $default_scale"

    if awk "BEGIN { exit !($scale > $default_scale) } "; then
        content+=$(echo "$monitor" | cut -d ',' -f-3 | xargs -I {} echo "monitor={}, $default_scale")
    else
        new_scale=$(awk "BEGIN {print $scale_factor * $scale}")
        content+=$(echo "$monitor" | cut -d ',' -f-3 | xargs -I {} echo "monitor={}, $new_scale")
    fi
done

~/.config/hypr/scripts/utils/update_file.sh "temp/monitor_scale.conf" "$content" && swww restore
