directory: ~/Music
library: ~/.local/state/beets/library.db
import:
    move: yes

# Plugins
plugins: albumtypes badfiles convert deezer edit embedart fetchart fish fromfilename info lastgenre lyrics spotify

convert:
    auto: yes
