"$schema" = 'https://starship.rs/config-schema.json'

palette = "colors"
add_newline = false

format       = """$directory$character"""
right_format = """$all"""

[character]
success_symbol = "[❯](color9 bold)"
error_symbol = "[❯](error)"

[directory]
truncation_length =      9
truncation_symbol =      '…/'
truncate_to_repo =       false
before_repo_root_style = "bold color1"
repo_root_style =        "bold color3"
read_only =              ' '

# Git
[git_status]
conflicted = "[󰚌${count}](red)" 
up_to_date = "[✓](green)"
ahead =      "[⇡${count}](yellow)"
behind =     "[⇣${count}](red)"
untracked =  "[+${count}](blue)" 
staged =     "[+${count}](green)" 
format =     '[\[$all_status$ahead_behind\]]($style) '

# Languages
[java]
symbol = ' '

[kotlin]
symbol = ' '

[gradle]
symbol = ' '

[lua]
symbol = ' '

[python]
symbol = ' '

[package]
symbol = ' '

# Themes
[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"

[palettes.colors]
color1 = '#93cdf6'
color2 = '#00344d'
color3 = '#c1c7ce'
color4 = '#1c2024'
color5 = '#00344d'
color6 = '#101417'
color7 = '#101417'
color8 = '#93cdf6'
color9 = '#cdc0e9'
error = '#ffb4ab'
red = '#ff0000'
green = '#00ff00'
yellow = '#ffff00'
blue = '#0000ff'
