add_newline = false

format       = """$directory$character"""
right_format = """
$username\
$hostname\
$localip\
$shlvl\
$singularity\
$kubernetes\
$vcsh\
$fossil_branch\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$hg_branch\
$pijul_channel\
$docker_context\
$package\
$c\
$cmake\
$cobol\
$daml\
$dart\
$deno\
$dotnet\
$elixir\
$elm\
$erlang\
$fennel\
$golang\
$guix_shell\
$haskell\
$haxe\
$helm\
$java\
$julia\
$kotlin\
$gradle\
$lua\
$nim\
$nodejs\
$ocaml\
$opa\
$perl\
$php\
$pulumi\
$purescript\
$python\
$raku\
$rlang\
$red\
$ruby\
$rust\
$scala\
$solidity\
$swift\
$terraform\
$vlang\
$vagrant\
$zig\
$buf\
$nix_shell\
$conda\
$meson\
$spack\
$memory_usage\
$aws\
$gcloud\
$openstack\
$azure\
$env_var\
$crystal\
$custom\
$sudo\
$cmd_duration\
$line_break\
$jobs\
$battery\
$time\
$status\
$os\
$container\
$shell
"""

[directory]
truncation_length =      9
truncation_symbol =      '…/'
truncate_to_repo =       false
before_repo_root_style = "bold purple"
repo_root_style =        "bold cyan"
read_only =              ' '

# Git
[git_status]
stashed =    "[${count}*](green)" 
modified =   "[󱩽${count}+](yellow)" 
deleted =    "[${count}-](red)" 
conflicted = "[󰚌${count}~](red)" 
up_to_date = "[✓](green)"
ahead =      "[⇡${count}](yellow)"
behind =     "[⇣${count}](red)"
untracked =  "[${count}?](blue)" 
staged =     "[${count}+](green)" 
format =     '[\[$all_status$ahead_behind\]]($style) '

# Languages
[java]
symbol = '☕'

[kotlin]
symbol = ' '

[gradle]
symbol = ' '

[lua]
symbol = ' '

[python]
symbol = ' '
