[theme]
background = "{color0}"
primary = "{color12}"
secondary = "{color3}"
title = "{color3}"
playing = "{color6}"
playing_selected = "{color9}"
playing_bg = "{color0}"
highlight = "{color9}"
highlight_bg = "{color0}"
error = "{color0}"
error_bg = "{color0}"
statusbar = "{color6}"
statusbar_progress = "{color3}"
statusbar_bg = "{color0}"
cmdline = "{color0}"
cmdline_bg = "{color0}"
search_match = "{color11}"
