vim.g.mapleader = " "
vim.g.maplocalleader = "\\"
vim.g.have_nerd_font = true

local opt = vim.opt
opt.number = true
opt.wrap = false
opt.linebreak = false
opt.shiftwidth = 4
opt.clipboard = "unnamedplus"
opt.signcolumn = "yes"
opt.scrolloff = 15
opt.sidescrolloff = 15
opt.hlsearch = true
opt.termguicolors = true
opt.cursorline = true
opt.undofile = true
opt.swapfile = false
opt.backup = false
opt.inccommand = "split"
