command_key = ":"
initial_screen = "library"
use_nerdfont = true
flip_status_indicators = false
# backend = <String>
# backend_device = <String>
audio_cache = true
# audio_cache_size = <Number>
volnorm = false
volnorm_pregain = 0.0
default_keybindings = true
notify = false
bitrate = 320
gapless = true
shuffle = true
repeat = "playlist"
playback_state = "Paused"
library_tabs = ["tracks", "albums", "artists", "playlists", "podcasts", "browse"]
cover_max_scale = 1.5
hide_display_names = false
statusbar_format = "%title - %artists"


[track_format]
left = "[%saved] %title "
center = "%artists "
right = "%duration"


[notification_format]
title = "#f89100"
body = "%artists - %duration"


[keybindings]
"Backspace" = "noop"
"Shift+q" = "quit"
"q" = "back"


[theme]
# background = "#020303"
primary = "#0087bf"
secondary = "#f89100"
title = "#f89100"
playing = "#0077ca"
playing_selected = "#16009b"
playing_bg = "#040407"
highlight = "#16009b"
highlight_bg = "#040407"
error = "#040407"
error_bg = "#040407"
statusbar = "#0077ca"
statusbar_progress = "#f89100"
statusbar_bg = "#040407"
cmdline = "#040407"
cmdline_bg = "#040407"
search_match = "#feb44d"
