#!/usr/bin/env bash
# Auto-select cursor theme based on primary color
# Generated by Matugen

PRIMARY_COLOR="{{colors.primary.default.hex}}"

# Function to calculate color distance (simple RGB distance)
color_distance() {
    local r1=$((16#${1:1:2}))
    local g1=$((16#${1:3:2}))
    local b1=$((16#${1:5:2}))

    local r2=$((16#${2:1:2}))
    local g2=$((16#${2:3:2}))
    local b2=$((16#${2:5:2}))

    echo $(( (r1-r2)*(r1-r2) + (g1-g2)*(g1-g2) + (b1-b2)*(b1-b2) ))
}

# Catppuccin Macchiato color mappings (approximate)
declare -A CURSOR_COLORS=(
    ["catppuccin-macchiato-rosewater-cursors"]="#f4dbd6"
    ["catppuccin-macchiato-flamingo-cursors"]="#f0c6c6"
    ["catppuccin-macchiato-pink-cursors"]="#f5bde6"
    ["catppuccin-macchiato-mauve-cursors"]="#c6a0f6"
    ["catppuccin-macchiato-red-cursors"]="#ed8796"
    ["catppuccin-macchiato-maroon-cursors"]="#ee99a0"
    ["catppuccin-macchiato-peach-cursors"]="#f5a97f"
    ["catppuccin-macchiato-yellow-cursors"]="#eed49f"
    ["catppuccin-macchiato-green-cursors"]="#a6da95"
    ["catppuccin-macchiato-teal-cursors"]="#8bd5ca"
    ["catppuccin-macchiato-sky-cursors"]="#91d7e3"
    ["catppuccin-macchiato-sapphire-cursors"]="#7dc4e4"
    ["catppuccin-macchiato-blue-cursors"]="#8aadf4"
    ["catppuccin-macchiato-lavender-cursors"]="#b7bdf8"
)

# Find closest matching cursor theme
min_distance=999999999
selected_theme="catppuccin-macchiato-blue-cursors"

for theme in "${!CURSOR_COLORS[@]}"; do
    dist=$(color_distance "$PRIMARY_COLOR" "${CURSOR_COLORS[$theme]}")
    if [ $dist -lt $min_distance ]; then
        min_distance=$dist
        selected_theme=$theme
    fi
done

echo "Selected cursor theme: $selected_theme (primary color: $PRIMARY_COLOR)"

# Update GTK cursor settings
gsettings set org.gnome.desktop.interface cursor-theme "$selected_theme"

# Update Hyprland cursor
hyprctl setcursor "$selected_theme" 24

# Update environment for new apps
export XCURSOR_THEME="$selected_theme"
