# Fish shell theme generated by matugen

set --global fish_color_normal {{colors.on_surface.default.hex_stripped}}
set --global fish_color_command {{colors.primary.default.hex_stripped}}
set --global fish_color_param {{colors.secondary.default.hex_stripped}}
set --global fish_color_keyword {{colors.primary.default.hex_stripped}}
set --global fish_color_quote {{colors.tertiary.default.hex_stripped}}
set --global fish_color_redirection {{colors.tertiary.default.hex_stripped}} --bold
set --global fish_color_end {{colors.on_surface_variant.default.hex_stripped}}
set --global fish_color_comment {{colors.outline.default.hex_stripped}}
set --global fish_color_error {{colors.error.default.hex_stripped}}
set --global fish_color_escape {{colors.tertiary_fixed_dim.default.hex_stripped}}
set --global fish_color_operator {{colors.tertiary_fixed_dim.default.hex_stripped}}
set --global fish_color_autosuggestion {{colors.outline.default.hex_stripped}}
set --global fish_color_cancel -r
set --global fish_color_cwd {{colors.primary.default.hex_stripped}}
set --global fish_color_cwd_root {{colors.error.default.hex_stripped}}
set --global fish_color_user {{colors.secondary.default.hex_stripped}}
set --global fish_color_host {{colors.on_surface.default.hex_stripped}}
set --global fish_color_host_remote {{colors.tertiary.default.hex_stripped}}
set --global fish_color_status {{colors.error.default.hex_stripped}}
set --global fish_color_valid_path --underline
set --global fish_color_history_current --bold
set --global fish_color_search_match --background={{colors.surface_container.default.hex_stripped}}
set --global fish_color_selection --background={{colors.surface_container_high.default.hex_stripped}}
set --global fish_pager_color_completion {{colors.on_surface.default.hex_stripped}}
set --global fish_pager_color_description {{colors.outline.default.hex_stripped}}
set --global fish_pager_color_prefix {{colors.primary.default.hex_stripped}} --bold --underline
set --global fish_pager_color_progress {{colors.on_primary.default.hex_stripped}} --background={{colors.primary.default.hex_stripped}}
set --global fish_pager_color_selected_background -r
